wordpress:
  image: wordpress
  working_dir: /var/www/html
  volumes:
    - /var/www/html/:/var/www/html
  links:
    - wordpress_db:mysql
  ports:
    - 80:80

wordpress_db:
  image: mariadb
  volumes:
    - /var/lib/mysql:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: wordpress

phpmyadmin:
  image: corbinu/docker-phpmyadmin
  links:
    - wordpress_db:mysql
  ports:
    - 8080:80
  environment:
    MYSQL_USERNAME: root
    MYSQL_ROOT_PASSWORD: wordpress
